import type { Metadata } from "next"
import Link from "next/link"
import { notFound } from "next/navigation"
import { ExternalLink } from "lucide-react"

import { CompareToggle } from "@/components/compare-toggle"
import { NicheBadges, SiteFavicon, SiteList } from "@/components/site-list"
import { Button } from "@/components/ui/button"
import { getSite, searchSites } from "@/lib/freeserp"
import { builderLabel, formatDate } from "@/lib/format"
import { getNicheByName } from "@/lib/niches"

export const revalidate = 86400

function normalize(raw: string) {
  return decodeURIComponent(raw).toLowerCase()
}

export async function generateMetadata(props: PageProps<"/site/[domain]">): Promise<Metadata> {
  const domain = normalize((await props.params).domain)
  const site = await getSite(domain)
  if (!site) return { title: "Startup not found" }
  return {
    title: `${site.domain}: ${site.title ?? "AI startup profile"}`,
    description: site.ai_summary?.slice(0, 160) ?? `Profile of ${site.domain}, an AI startup.`,
    alternates: { canonical: `/site/${site.domain}` },
  }
}

function Fact({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex justify-between gap-4 border-b py-3 last:border-b-0">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="text-right">{children}</dd>
    </div>
  )
}

export default async function SitePage(props: PageProps<"/site/[domain]">) {
  const domain = normalize((await props.params).domain)
  const site = await getSite(domain)
  if (!site) notFound()

  const mainNiche = site.ai_categories?.[0]
  // Similar startups: same main niche, matched on the site's own title words.
  const similar = mainNiche
    ? await searchSites({ niche: mainNiche, q: site.title?.split(/[|–—:-]/)[0], size: 7 }, 86400)
    : null
  const similarSites = similar?.results.filter((s) => s.domain !== site.domain).slice(0, 6) ?? []
  const niche = mainNiche ? getNicheByName(mainNiche) : undefined

  return (
    <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-10 sm:px-6">
      <div className="grid gap-10 lg:grid-cols-[2fr_1fr]">
        <div className="flex flex-col gap-6">
          <div className="flex items-center gap-4">
            <SiteFavicon domain={site.domain} size={48} />
            <div className="flex min-w-0 flex-col">
              <h1 className="truncate text-3xl font-bold tracking-tight sm:text-4xl">{site.domain}</h1>
              {site.title && <p className="text-muted-foreground">{site.title}</p>}
            </div>
          </div>
          {site.ai_summary && <p className="max-w-prose text-lg leading-relaxed">{site.ai_summary}</p>}
          <NicheBadges categories={site.ai_categories} />
          <div className="flex flex-wrap gap-2">
            <Button asChild>
              <a href={site.url} target="_blank" rel="noopener noreferrer nofollow">
                Visit {site.domain}
                <ExternalLink data-icon="inline-end" />
              </a>
            </Button>
            <CompareToggle domain={site.domain} />
          </div>
          <p className="text-sm text-muted-foreground">
            Summary generated by FreeSerp from the site&apos;s homepage.
          </p>
        </div>

        <dl className="h-fit rounded-xl border px-5 py-2">
          <Fact label="Domain Rating">{site.dr != null ? site.dr : "Not rated yet"}</Fact>
          <Fact label="Indexed by FreeSerp">{formatDate(site.went_live)}</Fact>
          <Fact label="Domain zone">{site.tld ? `.${site.tld}` : "Unknown"}</Fact>
          <Fact label="Built with">{builderLabel(site.ai_source) ?? "Unknown"}</Fact>
          <Fact label="Hosting">{site.webserver ?? "Unknown"}</Fact>
        </dl>
      </div>

      {similarSites.length > 0 && (
        <section aria-labelledby="similar-heading" className="flex flex-col gap-4">
          <div className="flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between">
            <div className="flex flex-col gap-1">
              <h2 id="similar-heading" className="text-2xl font-semibold tracking-tight">
                Similar startups
              </h2>
              <p className="text-muted-foreground">Close matches in {mainNiche}.</p>
            </div>
            {niche && (
              <Button asChild variant="outline">
                <Link href={`/niche/${niche.slug}`}>Explore {niche.name}</Link>
              </Button>
            )}
          </div>
          <SiteList sites={similarSites} />
        </section>
      )}
    </div>
  )
}
